name: Node cicd

permissions:
  contents: write

on: 
  push:
    paths:
      - "*.js"
      - ".github/workflows/cicd.yml"

  release:
    types: [published]

jobs:
  setup-node:
    name: Setup Node.js
    runs-on: ubuntu-latest
    steps:
     - name: Checkout repository
        uses: actions/checkout@v6

     - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

     - name: Install dependencies
        run: npm ci

     - name: upload workspace as artifact
        uses: actions/upload-artifact@v6
        with:
          name: node_workspace
          path: ./
  

      
